package de.madem.homium.constants

const val REQUEST_TAKE_PHOTO = 1

const val REQUEST_CODE_SHOPPING = 100
const val REQUEST_CODE_RECIPES = 200
const val REQUEST_CODE_ADD_INGREDIENT = 201
const val REQUEST_CODE_COOK_RECIPE = 205
const val REQUEST_CODE_INVENTORY = 300
const val REQUEST_CODE_SPEECH = 500
const val REQUEST_CODE_EDIT_RECIPE_FROM_PRESENTATION = 202
