package de.madem.homium.constants

//Settings
const val SHAREDPREFERENCE_NAMESPACEKEY_SETTINGS: String = "Shared_Preferences_NSKey_Settings"
const val SHAREDPREFERENCE_SETTINGS_PREFERENCEKEY_DATABASE_INITIALIZED = "Shared_Preferences_Settings_databaseInizialized"
const val SHAREDPREFERENCE_SETTINGS_PREFERENCEKEY_ONBOARDING_COMPLETED = "Shared_Preferences_Settings_onboardingCompleted"
const val SHAREDPREFERENCE_SETTINGS_PREFERENCEKEY_VIBRATION_ENABLED = "Shared_Preferences_Settings_vibrationEnabled"
const val SHAREDPREFERENCE_SETTINGS_PREFERENCEKEY_SHOPPING_SORT = "Shared_Preferences_Settings_sortedShoppingRadioId"
const val SHAREDPREFERENCE_SETTINGS_PREFERENCEKEY_DELETE_QUESTION_SPEECH_ASSISTENT_ALLOWED = "Shared_Preferences_Settings_deleteQuestionSpeechAssistentAllowed"
const val SHAREDPREFERENCE_SETTINGS_PREFERENCEKEY_SHOPPING_TO_INVENTORY = "Shared_Preferences_Settings_shoppingToInventory"

const val SHARED_PREFERENCE_SETTING_VALUE_SHOPPING_SORT_NORMAL = "Shopping_Sort_NORMAL"
const val SHARED_PREFERENCE_SETTING_VALUE_SHOPPING_SORT_REVERSED = "Shopping_Sort_REVERSED"